export default [
  {
    login: 'kimnguyen137',
    id: 21245559,
    node_id: 'MDQ6VXNlcjIxMjQ1NTU5',
    avatar_url: 'https://avatars.githubusercontent.com/u/21245559?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kimnguyen137',
    html_url: 'https://github.com/kimnguyen137',
    followers_url: 'https://api.github.com/users/kimnguyen137/followers',
    following_url:
      'https://api.github.com/users/kimnguyen137/following{/other_user}',
    gists_url: 'https://api.github.com/users/kimnguyen137/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/kimnguyen137/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/kimnguyen137/subscriptions',
    organizations_url: 'https://api.github.com/users/kimnguyen137/orgs',
    repos_url: 'https://api.github.com/users/kimnguyen137/repos',
    events_url: 'https://api.github.com/users/kimnguyen137/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/kimnguyen137/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'cmphan',
    id: 47398461,
    node_id: 'MDQ6VXNlcjQ3Mzk4NDYx',
    avatar_url: 'https://avatars.githubusercontent.com/u/47398461?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/cmphan',
    html_url: 'https://github.com/cmphan',
    followers_url: 'https://api.github.com/users/cmphan/followers',
    following_url: 'https://api.github.com/users/cmphan/following{/other_user}',
    gists_url: 'https://api.github.com/users/cmphan/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/cmphan/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/cmphan/subscriptions',
    organizations_url: 'https://api.github.com/users/cmphan/orgs',
    repos_url: 'https://api.github.com/users/cmphan/repos',
    events_url: 'https://api.github.com/users/cmphan/events{/privacy}',
    received_events_url: 'https://api.github.com/users/cmphan/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'KeithDinh',
    id: 52475783,
    node_id: 'MDQ6VXNlcjUyNDc1Nzgz',
    avatar_url: 'https://avatars.githubusercontent.com/u/52475783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/KeithDinh',
    html_url: 'https://github.com/KeithDinh',
    followers_url: 'https://api.github.com/users/KeithDinh/followers',
    following_url:
      'https://api.github.com/users/KeithDinh/following{/other_user}',
    gists_url: 'https://api.github.com/users/KeithDinh/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/KeithDinh/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/KeithDinh/subscriptions',
    organizations_url: 'https://api.github.com/users/KeithDinh/orgs',
    repos_url: 'https://api.github.com/users/KeithDinh/repos',
    events_url: 'https://api.github.com/users/KeithDinh/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/KeithDinh/received_events',
    type: 'User',
    site_admin: false,
  },
];
